### ISSUE TITLE
Error when trying to play music

### ISSUE THREAD

**Issue by Rotekoppen** [saanuregh/yet-another-discord.js-musicbot-addon#111]
```
[COMMAND] TYPE:PLAY QUERY:baba yetu AUTHOR_ID:164420487441547264 SERVERID:694141455375269990
[COMMAND] TYPE:PLAY DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/synced/projects/chb/captain-hooks-brain/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) SERVERID:694141455375269990
(node:45495) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/synced/projects/chb/captain-hooks-brain/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:45495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't know why this happens...
Please tell me if I need to include some logs or such!

**Comment by Rotekoppen** [comment]
Okay, its seems i've found the issue. I haven't activated my api, so it sent an object to the note() causing this error.

**Comment by Poerntii** [comment]
What do you mean? I have the same issue but Googles APIs is telling me that my API key is activated correctly.

**Comment by SimonLeclere** [comment]
I have the same issue and I don't know how to fix it :(
